-- DIGUL DIGUL weekly leaderboard / event verification
-- Browser clients never receive SUPABASE_SERVICE_ROLE_KEY.

create extension if not exists pgcrypto;

create table if not exists public.digul_games (
  game_id text primary key,
  store_id text not null,
  week_key text not null,
  player_hash text not null,
  nickname text not null check (char_length(nickname) between 2 and 10),
  score integer not null default 0 check (score between 0 and 1000000),
  max_level integer not null default 1 check (max_level between 1 and 11),
  last_seq integer not null default 0,
  drop_count integer not null default 0,
  merge_count integer not null default 0,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists digul_games_player_idx
  on public.digul_games (store_id, week_key, player_hash, score desc);

create table if not exists public.digul_game_events (
  id bigint generated by default as identity primary key,
  game_id text not null references public.digul_games(game_id) on delete cascade,
  seq integer not null,
  event_type text not null check (event_type in ('drop','merge')),
  from_level integer,
  to_level integer,
  points integer not null default 0,
  client_at_ms bigint,
  created_at timestamptz not null default now(),
  unique (game_id, seq)
);

create index if not exists digul_events_game_idx
  on public.digul_game_events (game_id, seq);

create table if not exists public.digul_weekly_best (
  store_id text not null,
  week_key text not null,
  player_hash text not null,
  nickname text not null check (char_length(nickname) between 2 and 10),
  score integer not null default 0 check (score between 0 and 1000000),
  achieved_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (store_id, week_key, player_hash)
);

create index if not exists digul_weekly_rank_idx
  on public.digul_weekly_best (store_id, week_key, score desc, achieved_at asc);

create or replace view public.digul_weekly_ranked as
select
  store_id,
  week_key,
  player_hash,
  nickname,
  score,
  achieved_at,
  row_number() over (
    partition by store_id, week_key
    order by score desc, achieved_at asc
  )::integer as rank
from public.digul_weekly_best;

alter table public.digul_games enable row level security;
alter table public.digul_game_events enable row level security;
alter table public.digul_weekly_best enable row level security;

-- No anon write policies. The Edge Function uses the service-role key.
comment on table public.digul_games is 'DIGUL DIGUL game sessions. Score is recomputed from accepted events.';
comment on table public.digul_game_events is 'Ordered drop/merge events used to prevent duplicate scoring.';
comment on table public.digul_weekly_best is 'One verified weekly best per player ID. Weeks are Monday-Sunday in Asia/Seoul.';
